<?php

declare(strict_types=1);

/**
 * @file
 * Provides a report builder entity type.
 */

use Drupal\Core\Render\Element;
use Drupal\user\UserInterface;

/**
 * Implements hook_theme().
 */
function report_builder_theme(): array {
  return [
    'report_builder' => ['render element' => 'elements'],
  ];
}

/**
 * Prepares variables for report builder templates.
 *
 * Default template: report-builder.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the report builder information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_report_builder(array &$variables): void {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Implements hook_user_cancel().
 */
function report_builder_user_cancel($edit, UserInterface $account, $method): void {
  switch ($method) {
    case 'user_cancel_block_unpublish':
      // Unpublish report builders.
      $storage = \Drupal::entityTypeManager()->getStorage('report_builder');
      $report_builder_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->condition('status', 1)
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($report_builder_ids) as $report_builder) {
        $report_builder->set('status', FALSE)->save();
      }
      break;

    case 'user_cancel_reassign':
      // Anonymize report builders.
      $storage = \Drupal::entityTypeManager()->getStorage('report_builder');
      $report_builder_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($report_builder_ids) as $report_builder) {
        $report_builder->setOwnerId(0)->save();
      }
      break;
  }
}

/**
 * Implements hook_ENTITY_TYPE_predelete() for user entities.
 */
function report_builder_user_predelete(UserInterface $account): void {
  // Delete report builders that belong to this account.
  $storage = \Drupal::entityTypeManager()->getStorage('report_builder');
  $report_builder_ids = $storage->getQuery()
    ->condition('uid', $account->id())
    ->accessCheck(FALSE)
    ->execute();
  $storage->delete(
    $storage->loadMultiple($report_builder_ids)
  );
  // Delete old revisions.
  $report_builder_ids = $storage->getQuery()
    ->allRevisions()
    ->condition('uid', $account->id())
    ->accessCheck(FALSE)
    ->execute();
  foreach (array_keys($report_builder_ids) as $revision_id) {
    $storage->deleteRevision($revision_id);
  }
}
